// Not yet implemented...

// Products Data
export const products = [
    {
      id: "1",
      name: "Cotton Kurta - Blue",
      code: "CK001",
      fabricType: "Cotton",
      size: "L",
      color: "Blue",
      purchaseCost: 600,
      minSalePrice: 900,
      maxSalePrice: 1500,
      currentPrice: 1200,
      stock: 15,
      supplier: "Textile Mills Ltd",
      batchInfo: "Batch-2024-001",
      status: "active",
      createdDate: "2024-01-15",
    },
    {
      id: "2",
      name: "Silk Dupatta - Red",
      code: "SD002",
      fabricType: "Silk",
      size: "Standard",
      color: "Red",
      purchaseCost: 400,
      minSalePrice: 650,
      maxSalePrice: 1000,
      currentPrice: 800,
      stock: 8,
      supplier: "Silk Weavers Co",
      batchInfo: "Batch-2024-002",
      status: "active",
      createdDate: "2024-01-20",
    },
    {
      id: "3",
      name: "Linen Shirt - White",
      code: "LS003",
      fabricType: "Linen",
      size: "M",
      color: "White",
      purchaseCost: 800,
      minSalePrice: 1200,
      maxSalePrice: 2000,
      currentPrice: 1500,
      stock: 12,
      supplier: "Premium Fabrics",
      batchInfo: "Batch-2024-003",
      status: "active",
      createdDate: "2024-02-01",
    },
    {
      id: "4",
      name: "Cotton Pants - Black",
      code: "CP004",
      fabricType: "Cotton",
      size: "M",
      color: "Black",
      purchaseCost: 500,
      minSalePrice: 700,
      maxSalePrice: 1200,
      currentPrice: 900,
      stock: 20,
      supplier: "Fashion Hub",
      batchInfo: "Batch-2024-004",
      status: "active",
      createdDate: "2024-01-25",
    },
    {
      id: "5",
      name: "Silk Saree - Green",
      code: "SS005",
      fabricType: "Silk",
      size: "Standard",
      color: "Green",
      purchaseCost: 2000,
      minSalePrice: 3000,
      maxSalePrice: 4500,
      currentPrice: 3500,
      stock: 5,
      supplier: "Silk Weavers Co",
      batchInfo: "Batch-2024-005",
      status: "active",
      createdDate: "2024-02-05",
    },
  ]
  
  // Inventory Data
  export const inventoryItems = [
    {
      id: "1",
      name: "Cotton Kurta - Blue",
      code: "CK001",
      category: "Kurtas",
      currentStock: 15,
      minStock: 20,
      maxStock: 100,
      reservedStock: 3,
      availableStock: 12,
      status: "available",
      location: "Rack A-1",
      lastUpdated: "2024-01-15",
      supplier: "Textile Mills Ltd",
      purchasePrice: 600,
      salePrice: 1200,
      batchNumber: "B2024001",
    },
    {
      id: "2",
      name: "Silk Dupatta - Red",
      code: "SD002",
      category: "Dupatta",
      currentStock: 5,
      minStock: 15,
      maxStock: 50,
      reservedStock: 1,
      availableStock: 4,
      status: "available",
      location: "Rack B-2",
      lastUpdated: "2024-01-20",
      supplier: "Silk Weavers Co",
      purchasePrice: 400,
      salePrice: 800,
      batchNumber: "B2024002",
    },
    {
      id: "3",
      name: "Linen Shirt - White",
      code: "LS003",
      category: "Shirts",
      currentStock: 0,
      minStock: 10,
      maxStock: 40,
      reservedStock: 0,
      availableStock: 0,
      status: "out-of-stock",
      location: "Rack C-1",
      lastUpdated: "2024-02-01",
      supplier: "Premium Fabrics",
      purchasePrice: 800,
      salePrice: 1500,
      batchNumber: "B2024003",
    },
    {
      id: "4",
      name: "Cotton Pants - Black",
      code: "CP004",
      category: "Pants",
      currentStock: 8,
      minStock: 15,
      maxStock: 60,
      reservedStock: 2,
      availableStock: 6,
      status: "available",
      location: "Rack D-1",
      lastUpdated: "2024-01-25",
      supplier: "Fashion Hub",
      purchasePrice: 500,
      salePrice: 900,
      batchNumber: "B2024004",
    },
  ]
  
  // Stock Movements Data
  export const stockMovements = [
    {
      id: "1",
      itemId: "1",
      itemName: "Cotton Kurta - Blue",
      type: "in",
      quantity: 25,
      reason: "New stock received",
      staff: "Ahmed Ali",
      date: "2024-01-15",
      reference: "PO-2024-001",
    },
    {
      id: "2",
      itemId: "1",
      itemName: "Cotton Kurta - Blue",
      type: "out",
      quantity: 10,
      reason: "Sale",
      staff: "Fatima Khan",
      date: "2024-01-16",
      reference: "SALE-2024-045",
    },
    {
      id: "3",
      itemId: "2",
      itemName: "Silk Dupatta - Red",
      type: "damaged",
      quantity: 2,
      reason: "Fabric tear during handling",
      staff: "Hassan Sheikh",
      date: "2024-01-18",
      reference: "DMG-2024-003",
    },
  ]
  
  // Credit & Debit Ledger Data
  export const creditEntries = [
    {
      id: "1",
      customerName: "Ali Hassan",
      customerPhone: "+92-300-1234567",
      amount: 15000,
      dueDate: "2024-02-15",
      saleDate: "2024-01-15",
      invoiceNumber: "INV-2024-001",
      status: "pending",
      paidAmount: 0,
      remainingAmount: 15000,
      paymentHistory: [],
      notes: "Wedding dress order - 3 pieces",
    },
    {
      id: "2",
      customerName: "Fatima Khan",
      customerPhone: "+92-301-9876543",
      amount: 8500,
      dueDate: "2024-02-10",
      saleDate: "2024-01-20",
      invoiceNumber: "INV-2024-002",
      status: "partial",
      paidAmount: 3000,
      remainingAmount: 5500,
      paymentHistory: [
        {
          id: "1",
          amount: 3000,
          date: "2024-01-25",
          method: "Cash",
          reference: "CASH-001",
          notes: "Partial payment",
        },
      ],
      notes: "Regular customer - good payment history",
    },
    {
      id: "3",
      customerName: "Ahmed Sheikh",
      customerPhone: "+92-302-5555555",
      amount: 12000,
      dueDate: "2024-01-30",
      saleDate: "2024-01-10",
      invoiceNumber: "INV-2024-003",
      status: "overdue",
      paidAmount: 0,
      remainingAmount: 12000,
      paymentHistory: [],
      notes: "Multiple reminders sent",
    },
  ]
  
  export const debitEntries = [
    {
      id: "1",
      supplierName: "Textile Mills Ltd",
      supplierPhone: "+92-42-1111111",
      amount: 45000,
      dueDate: "2024-02-20",
      purchaseDate: "2024-01-20",
      invoiceNumber: "PUR-2024-001",
      status: "pending",
      paidAmount: 0,
      remainingAmount: 45000,
      paymentHistory: [],
      description: "Cotton fabric - 100 meters",
      category: "Raw Material",
    },
    {
      id: "2",
      supplierName: "Silk Weavers Co",
      supplierPhone: "+92-42-2222222",
      amount: 25000,
      dueDate: "2024-02-15",
      purchaseDate: "2024-01-18",
      invoiceNumber: "PUR-2024-002",
      status: "partial",
      paidAmount: 10000,
      remainingAmount: 15000,
      paymentHistory: [
        {
          id: "1",
          amount: 10000,
          date: "2024-01-28",
          method: "Bank Transfer",
          reference: "TXN-123456",
          notes: "Advance payment",
        },
      ],
      description: "Premium silk fabric - 50 meters",
      category: "Raw Material",
    },
  ]
  
  // Bargaining Records Data
  export const bargainRecords = [
    {
      id: "1",
      date: "2024-01-15",
      time: "14:30",
      productName: "Cotton Kurta - Blue",
      productCode: "CK001",
      originalPrice: 1200,
      finalPrice: 950,
      discountAmount: 250,
      discountPercentage: 20.8,
      customerName: "Ali Hassan",
      customerPhone: "+92-300-1234567",
      staffMember: "Ahmed Ali",
      reason: "Regular customer discount",
      invoiceNumber: "INV-2024-001",
      category: "Kurtas",
      profitMargin: 35,
      status: "approved",
    },
    {
      id: "2",
      date: "2024-01-15",
      time: "16:45",
      productName: "Silk Dupatta - Red",
      productCode: "SD002",
      originalPrice: 800,
      finalPrice: 650,
      discountAmount: 150,
      discountPercentage: 18.8,
      customerName: "Fatima Khan",
      customerPhone: "+92-301-9876543",
      staffMember: "Fatima Khan",
      reason: "Bulk purchase discount",
      invoiceNumber: "INV-2024-002",
      category: "Dupatta",
      profitMargin: 42,
      status: "approved",
    },
    {
      id: "3",
      date: "2024-01-16",
      time: "11:20",
      productName: "Linen Shirt - White",
      productCode: "LS003",
      originalPrice: 1500,
      finalPrice: 1250,
      discountAmount: 250,
      discountPercentage: 16.7,
      customerName: "Hassan Sheikh",
      staffMember: "Hassan Sheikh",
      reason: "Minor defect compensation",
      invoiceNumber: "INV-2024-003",
      category: "Shirts",
      profitMargin: 28,
      status: "approved",
    },
    {
      id: "4",
      date: "2024-01-16",
      time: "17:10",
      productName: "Cotton Pants - Black",
      productCode: "CP004",
      originalPrice: 900,
      finalPrice: 600,
      discountAmount: 300,
      discountPercentage: 33.3,
      customerName: "Sara Ahmed",
      staffMember: "Ahmed Ali",
      reason: "End of season clearance",
      invoiceNumber: "INV-2024-004",
      category: "Pants",
      profitMargin: 15,
      status: "approved",
    },
  ]
  
  // Employee Data
  export const employees = [
    {
      id: "1",
      name: "Ahmed Ali",
      email: "ahmed.ali@powerproject.com",
      phone: "+92-300-1234567",
      position: "Sales Manager",
      department: "Sales",
      joinDate: "2023-01-15",
      salary: 45000,
      commission: 2.5,
      status: "active",
      address: "123 Main Street, Lahore",
      emergencyContact: "+92-301-7654321",
      bankAccount: "1234567890",
      cnic: "12345-6789012-3",
      monthlySales: 125000,
      monthlyTarget: 150000,
      attendanceRate: 95,
      performanceScore: 88,
      totalSales: 1250000,
      totalCommission: 31250,
    },
    {
      id: "2",
      name: "Fatima Khan",
      email: "fatima.khan@powerproject.com",
      phone: "+92-301-9876543",
      position: "Sales Associate",
      department: "Sales",
      joinDate: "2023-03-20",
      salary: 35000,
      commission: 2.0,
      status: "active",
      address: "456 Garden Town, Lahore",
      emergencyContact: "+92-302-1234567",
      bankAccount: "0987654321",
      cnic: "54321-0987654-3",
      monthlySales: 98000,
      monthlyTarget: 100000,
      attendanceRate: 92,
      performanceScore: 85,
      totalSales: 980000,
      totalCommission: 19600,
    },
    {
      id: "3",
      name: "Hassan Sheikh",
      email: "hassan.sheikh@powerproject.com",
      phone: "+92-302-5555555",
      position: "Store Assistant",
      department: "Operations",
      joinDate: "2023-06-10",
      salary: 28000,
      commission: 1.5,
      status: "active",
      address: "789 Model Town, Lahore",
      emergencyContact: "+92-303-9876543",
      bankAccount: "1122334455",
      cnic: "11111-2222233-4",
      monthlySales: 65000,
      monthlyTarget: 80000,
      attendanceRate: 88,
      performanceScore: 78,
      totalSales: 650000,
      totalCommission: 9750,
    },
    {
      id: "4",
      name: "Sara Ahmed",
      email: "sara.ahmed@powerproject.com",
      phone: "+92-304-1111111",
      position: "Cashier",
      department: "Operations",
      joinDate: "2023-08-01",
      salary: 25000,
      commission: 1.0,
      status: "on-leave",
      address: "321 DHA Phase 5, Lahore",
      emergencyContact: "+92-305-5555555",
      bankAccount: "5566778899",
      cnic: "55555-6666677-8",
      monthlySales: 45000,
      monthlyTarget: 60000,
      attendanceRate: 85,
      performanceScore: 72,
      totalSales: 450000,
      totalCommission: 4500,
    },
  ]
  
  // Attendance Records Data
  export const attendanceRecords = [
    {
      id: "1",
      employeeId: "1",
      employeeName: "Ahmed Ali",
      date: "2024-01-15",
      checkIn: "09:00",
      checkOut: "18:00",
      hoursWorked: 9,
      status: "present",
      notes: "",
    },
    {
      id: "2",
      employeeId: "2",
      employeeName: "Fatima Khan",
      date: "2024-01-15",
      checkIn: "09:15",
      checkOut: "18:00",
      hoursWorked: 8.75,
      status: "late",
      notes: "Traffic delay",
    },
    {
      id: "3",
      employeeId: "3",
      employeeName: "Hassan Sheikh",
      date: "2024-01-15",
      checkIn: "09:00",
      checkOut: "13:00",
      hoursWorked: 4,
      status: "half-day",
      notes: "Medical appointment",
    },
  ]
  
  // Salary Records Data
  export const salaryRecords = [
    {
      id: "1",
      employeeId: "1",
      employeeName: "Ahmed Ali",
      month: "January 2024",
      basicSalary: 45000,
      commission: 3125,
      bonus: 5000,
      deductions: 2000,
      totalSalary: 51125,
      status: "paid",
      paidDate: "2024-01-31",
    },
    {
      id: "2",
      employeeId: "2",
      employeeName: "Fatima Khan",
      month: "January 2024",
      basicSalary: 35000,
      commission: 1960,
      bonus: 2000,
      deductions: 1500,
      totalSalary: 37460,
      status: "paid",
      paidDate: "2024-01-31",
    },
    {
      id: "3",
      employeeId: "3",
      employeeName: "Hassan Sheikh",
      month: "January 2024",
      basicSalary: 28000,
      commission: 975,
      bonus: 1000,
      deductions: 1000,
      totalSalary: 28975,
      status: "pending",
    },
  ]
  
  // Disposal Records Data
  export const disposalRecords = [
    {
      id: "1",
      itemName: "Cotton Kurta - Blue",
      itemCode: "CK001",
      category: "Kurtas",
      originalPrice: 1200,
      disposalValue: 0,
      lossAmount: 1200,
      quantity: 2,
      disposalDate: "2024-01-15",
      reason: "Fabric tear during handling",
      condition: "damaged",
      disposalMethod: "discard",
      approvedBy: "Ahmed Ali",
      notes: "Damaged during customer trial, irreparable tear",
      batchNumber: "B2024001",
      supplierName: "Textile Mills Ltd",
    },
    {
      id: "2",
      itemName: "Silk Dupatta - Red",
      itemCode: "SD002",
      category: "Dupatta",
      originalPrice: 800,
      disposalValue: 200,
      lossAmount: 600,
      quantity: 1,
      disposalDate: "2024-01-18",
      reason: "Color fading issue",
      condition: "defective",
      disposalMethod: "sell-discount",
      approvedBy: "Fatima Khan",
      notes: "Sold at 75% discount due to color bleeding",
      batchNumber: "B2024002",
      supplierName: "Silk Weavers Co",
    },
    {
      id: "3",
      itemName: "Linen Shirt - White",
      itemCode: "LS003",
      category: "Shirts",
      originalPrice: 1500,
      disposalValue: 0,
      lossAmount: 1500,
      quantity: 1,
      disposalDate: "2024-01-20",
      reason: "Theft from store",
      condition: "stolen",
      disposalMethod: "discard",
      approvedBy: "Hassan Sheikh",
      notes: "Item missing from inventory, suspected theft",
      batchNumber: "B2024003",
      supplierName: "Premium Fabrics",
    },
    {
      id: "4",
      itemName: "Cotton Pants - Black",
      itemCode: "CP004",
      category: "Pants",
      originalPrice: 900,
      disposalValue: 450,
      lossAmount: 450,
      quantity: 3,
      disposalDate: "2024-01-22",
      reason: "End of season clearance",
      condition: "unsold",
      disposalMethod: "sell-discount",
      approvedBy: "Ahmed Ali",
      notes: "Slow-moving inventory, cleared at 50% discount",
      batchNumber: "B2024004",
      supplierName: "Fashion Hub",
    },
  ]
  
  // Sales Records Data
  export const salesRecords = [
    {
      id: "1",
      invoiceNumber: "INV-2024-001",
      date: "2024-01-15",
      time: "14:30",
      customerName: "Ali Hassan",
      customerPhone: "+92-300-1234567",
      customerType: "regular",
      items: [
        {
          id: "1",
          name: "Cotton Kurta - Blue",
          code: "CK001",
          quantity: 2,
          originalPrice: 1200,
          finalPrice: 950,
          discount: 250,
        },
        {
          id: "2",
          name: "Cotton Pants - Black",
          code: "CP004",
          quantity: 1,
          originalPrice: 900,
          finalPrice: 900,
          discount: 0,
        },
      ],
      subtotal: 2800,
      discount: 250,
      tax: 0,
      total: 2550,
      paymentMethod: "cash",
      paymentStatus: "paid",
      deliveryStatus: "pickup",
      staffMember: "Ahmed Ali",
      notes: "Regular customer, wedding purchase",
      returnStatus: "none",
    },
    {
      id: "2",
      invoiceNumber: "INV-2024-002",
      date: "2024-01-15",
      time: "16:45",
      customerName: "Fatima Khan",
      customerPhone: "+92-301-9876543",
      customerType: "vip",
      items: [
        {
          id: "1",
          name: "Silk Dupatta - Red",
          code: "SD002",
          quantity: 3,
          originalPrice: 800,
          finalPrice: 650,
          discount: 150,
        },
      ],
      subtotal: 2400,
      discount: 450,
      tax: 0,
      total: 1950,
      paymentMethod: "card",
      paymentStatus: "paid",
      deliveryStatus: "delivered",
      deliveryAddress: "123 Garden Town, Lahore",
      deliveryDate: "2024-01-16",
      staffMember: "Fatima Khan",
      notes: "VIP customer, bulk purchase discount",
      returnStatus: "none",
    },
    {
      id: "3",
      invoiceNumber: "INV-2024-003",
      date: "2024-01-16",
      time: "11:20",
      customerName: "Hassan Sheikh",
      customerPhone: "+92-302-5555555",
      customerType: "walk-in",
      items: [
        {
          id: "1",
          name: "Linen Shirt - White",
          code: "LS003",
          quantity: 1,
          originalPrice: 1500,
          finalPrice: 1250,
          discount: 250,
        },
      ],
      subtotal: 1500,
      discount: 250,
      tax: 0,
      total: 1250,
      paymentMethod: "mobile",
      paymentStatus: "paid",
      deliveryStatus: "pending",
      deliveryAddress: "456 Model Town, Lahore",
      deliveryDate: "2024-01-18",
      staffMember: "Hassan Sheikh",
      notes: "First-time customer",
      returnStatus: "none",
    },
    {
      id: "4",
      invoiceNumber: "INV-2024-004",
      date: "2024-01-16",
      time: "17:10",
      customerName: "Sara Ahmed",
      customerPhone: "+92-304-1111111",
      customerType: "regular",
      items: [
        {
          id: "1",
          name: "Cotton Kurta - Blue",
          code: "CK001",
          quantity: 1,
          originalPrice: 1200,
          finalPrice: 1200,
          discount: 0,
        },
      ],
      subtotal: 1200,
      discount: 0,
      tax: 0,
      total: 1200,
      paymentMethod: "credit",
      paymentStatus: "pending",
      deliveryStatus: "pickup",
      staffMember: "Ahmed Ali",
      notes: "Credit sale, 30 days payment terms",
      returnStatus: "none",
    },
  ]
  
  // Dashboard Data
  export const dashboardData = {
    salesData: {
      today: 15420,
      yesterday: 12350,
      month: 456780,
      lastMonth: 398650,
    },
    topBargainedItems: [
      { name: "Cotton Kurta - Blue", originalPrice: 1200, finalPrice: 950, discount: 21 },
      { name: "Silk Dupatta - Red", originalPrice: 800, finalPrice: 650, discount: 19 },
      { name: "Linen Shirt - White", originalPrice: 1500, finalPrice: 1250, discount: 17 },
    ],
    stockAlerts: [
      { item: "Cotton Fabric - Black", stock: 5, minStock: 20, status: "critical" },
      { item: "Silk Thread - Gold", stock: 12, minStock: 15, status: "low" },
      { item: "Buttons - Pearl", stock: 8, minStock: 25, status: "critical" },
    ],
    employeeSales: [
      { name: "Ahmed Ali", sales: 25400, target: 30000, performance: 85 },
      { name: "Fatima Khan", sales: 32100, target: 30000, performance: 107 },
      { name: "Hassan Sheikh", sales: 18900, target: 25000, performance: 76 },
    ],
  }
  
  // Reports Data
  export const reportsData = {
    salesData: [
      { month: "Jan", sales: 125000, profit: 45000, orders: 156 },
      { month: "Feb", sales: 142000, profit: 52000, orders: 178 },
      { month: "Mar", sales: 138000, profit: 48000, orders: 165 },
      { month: "Apr", sales: 165000, profit: 62000, orders: 198 },
      { month: "May", sales: 158000, profit: 58000, orders: 187 },
      { month: "Jun", sales: 175000, profit: 68000, orders: 210 },
    ],
    categoryData: [
      { name: "Kurtas", value: 35, sales: 245000, color: "#8884d8" },
      { name: "Dupatta", value: 25, sales: 175000, color: "#82ca9d" },
      { name: "Shirts", value: 20, sales: 140000, color: "#ffc658" },
      { name: "Pants", value: 15, sales: 105000, color: "#ff7300" },
      { name: "Others", value: 5, sales: 35000, color: "#00ff00" },
    ],
    employeePerformance: [
      { name: "Ahmed Ali", sales: 125000, target: 150000, commission: 3125 },
      { name: "Fatima Khan", sales: 98000, target: 100000, commission: 1960 },
      { name: "Hassan Sheikh", sales: 65000, target: 80000, commission: 975 },
      { name: "Sara Ahmed", sales: 45000, target: 60000, commission: 450 },
    ],
    inventoryData: [
      { category: "Kurtas", inStock: 145, lowStock: 12, outOfStock: 3 },
      { category: "Dupatta", inStock: 89, lowStock: 8, outOfStock: 2 },
      { category: "Shirts", inStock: 67, lowStock: 15, outOfStock: 5 },
      { category: "Pants", inStock: 123, lowStock: 6, outOfStock: 1 },
    ],
    customerData: [
      { type: "New Customers", count: 45, percentage: 35 },
      { type: "Returning Customers", count: 78, percentage: 60 },
      { type: "VIP Customers", count: 12, percentage: 5 },
    ],
    profitMarginData: [
      { product: "Cotton Kurta", margin: 45, sales: 25000 },
      { product: "Silk Dupatta", margin: 52, sales: 18000 },
      { product: "Linen Shirt", margin: 38, sales: 22000 },
      { product: "Cotton Pants", margin: 42, sales: 15000 },
    ],
  }
  